import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // <--- 1. Importamos Script
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        {/* <--- 2. Script de Google Maps con librería "places" */}
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyDOZ9gVgcmAr19Ol35AzFGiuYR_8v8Mx-4&libraries=places`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}