import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; 
import "./globals.css"; // <--- Correcto: globals.css (plural)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        {/* Script de Google Maps */}
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyDOZ9gVgcmAr19Ol35AzFGiuYR_8v8Mx-4&libraries=places`}
          strategy="beforeInteractive"
        />

        {/* Estilos del chat de n8n */}
        <link href="https://cdn.jsdelivr.net/npm/@n8n/chat/dist/style.css" rel="stylesheet" />
        
{/* Script del chat de n8n customizado para Dyzgo */}
        <script 
          type="module" 
          dangerouslySetInnerHTML={{ 
            __html: `
              import { createChat } from 'https://cdn.jsdelivr.net/npm/@n8n/chat/dist/chat.bundle.es.js';
              createChat({
                webhookUrl: 'AQUI_PEGA_LA_URL_QUE_COPIASTE',
                initialMessages: [
                  '¡Hola! 👋 Soy el asistente virtual de Dyzgo.',
                  '¿En qué te puedo ayudar hoy con tus eventos o entradas?'
                ],
                i18n: {
                  en: {
                    title: 'Soporte Dyzgo',
                    subtitle: 'Resolvemos tus dudas 24/7.',
                    footer: '',
                    getStarted: 'Nueva conversación',
                    inputPlaceholder: 'Escribe tu pregunta...',
                  },
                },
                theme: {
                  colors: {
                    primary: '#F04D6A', /* Aquí puedes poner el código HEX exacto de tu color rosado/rojo */
                  }
                }
              });
            ` 
          }} 
        />
      </body>
    </html>
  );
}
